version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: transfer_app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transfer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transfer_network

volumes:
  postgres_data:
    driver: local

networks:
  transfer_network:
    driver: bridge
